[build]
compiler = "clang"
cstandard = "gnu11"

[[targets]]
name = "libacetate"
src = "./engine/"
include_dir = "./engine/include/"
type = "dll"
cflags = "-g -Wall -Wextra"
libs = "-lvulkan -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -ldl -rdynamic -lm"
deps = []

[[targets]]
name = "testbed"
src = "./testbed/"
include_dir = "./testbed/include/"
type = "exe"
cflags = "-g -Wall -Wextra"
libs = "-ldl -rdynamic"
deps = ["libacetate"]
