[build]
compiler = "clang"

[[targets]]
name = "libacetate"
src = "./engine/"
include_dir = "./engine/include/"
type = "dll"
cflags = "-g -Wall -Wextra"
libs = "-lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer"
deps = []

[[targets]]
name = "testbed"
src = "./testbed/"
include_dir = "./testbed/include/"
type = "exe"
cflags = "-g -Wall -Wextra"
libs = ""
deps = ["libacetate"]
